version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_HOME_ASSISTANT_IP
      APP_PORT: 8123
      PROXY_AUTH_ADD: "false"

  server:
    image: homeassistant/home-assistant:2022.10.5@sha256:090d8cbd6f8675984ca1ca9d357d8aca97101c61f93f221e339731a702160887
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - ${APP_DATA_DIR}/configuration.yaml:/config/configuration.yaml
    networks:
      default:
        ipv4_address: $APP_HOME_ASSISTANT_IP
