version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_LNPLUS_IP
      APP_PORT: $APP_LNPLUS_PORT
  web:
    image: lightningnetworkplus/lnpclient:v0.1.12@sha256:fbd6deb094972b399ac693faee461bfb2808f183b36ad765e93dac9dab361418
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/lnd:ro
    environment:
      RAILS_ENV: $APP_LNPLUS_RAILS_ENVIRONMENT
      APP_LNPLUS_RAILS_ENVIRONMENT: $APP_LNPLUS_RAILS_ENVIRONMENT
      LN_IMPLEMENTATION: "LND"
      LN_SERVER_URL: $APP_LIGHTNING_NODE_IP:$APP_LIGHTNING_NODE_GRPC_PORT/
      MACAROON_PATH: "/lnd/data/chain/bitcoin/$APP_BITCOIN_NETWORK/admin.macaroon"
      CONFIG_PATH: "/lnd/lnd.conf"
      CERTIFICATE_PATH: "/lnd/tls.cert"
    networks:
      default:
        ipv4_address: $APP_LNPLUS_IP