version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: lnplus_web_1
      APP_PORT: 3777
  web:
    image: lightningnetworkplus/lnpclient:v0.1.13@sha256:80bf9ab775fd397dbe7cdecbb928b9978cbb973578692cce9e508b1bb1b22780
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/lnd:ro
    environment:
      RAILS_ENV: "production"
      LN_IMPLEMENTATION: "LND"
      LN_SERVER_URL: $APP_LIGHTNING_NODE_IP:$APP_LIGHTNING_NODE_GRPC_PORT/
      MACAROON_PATH: "/lnd/data/chain/bitcoin/$APP_BITCOIN_NETWORK/admin.macaroon"
      CONFIG_PATH: "/lnd/lnd.conf"
      CERTIFICATE_PATH: "/lnd/tls.cert"
    networks:
      default:
        ipv4_address: $APP_LNPLUS_IP