version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: lnplus_web_1
      APP_PORT: "3777"
      API_URL: "https://lightningnetwork.plus/api/2/"
  web:
    image: lightningnetworkplus/lnpclient:v0.1.18@sha256:acce636182497596ec443aaa6ac696e3bf36e581a1d84e8d172bde52093cd2d2
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/lnd:ro
    environment:
      LN_IMPLEMENTATION: "LND"
      LN_SERVER_URL: $APP_LIGHTNING_NODE_IP:$APP_LIGHTNING_NODE_GRPC_PORT/
      MACAROON_PATH: "/lnd/data/chain/bitcoin/$APP_BITCOIN_NETWORK/admin.macaroon"
      CONFIG_PATH: "/lnd/lnd.conf"
      CERTIFICATE_PATH: "/lnd/tls.cert"